
FROM node:latest

# On crée le dossier de base de l'app dans l'image
WORKDIR  /app

# ON copie le code source de l'application ici
COPY . .

# Installing angular CLI
RUN npm install -g @angular/cli




